name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 5"

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      DEBFULLNAME: "Fred Hornsey"
      DEBEMAIL: "hornseyf@objectcomputing.com"

    steps:
    - name: Install Ubuntu Packages
      run: |
        sudo apt-get update
        sudo apt-get install debhelper lintian

    - name: Checkout OpenDDS-Debian
      uses: actions/checkout@v4
      with:
        path: OpenDDS-Debian

    - name: Checkout OpenDDS
      uses: actions/checkout@v4
      with:
        repository: 'OpenDDS/OpenDDS'
        path: opendds-3.30
        ref: 'DDS-3.30'

    - name: Copy debian Directory
      run: cp -r OpenDDS-Debian/debian opendds-3.30/debian

    - name: Build Package
      run: |
        cd opendds-3.30
        dpkg-buildpackage -us -uc
        cd ..
        cp opendds_*.deb opendds.deb

    - name: Commit New Deb
      run: |
        cd opendds-3.30
        SHA=$(git rev-parse --short HEAD)
        cd ../OpenDDS-Debian
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git fetch --depth 1 origin ubuntu_20_04
        git checkout ubuntu_20_04
        cp ../opendds.deb opendds.deb
        git add opendds.deb
        git \
          -c 'user.email=actions@github.com' \
          -c 'user.name=GitHub Actions' \
          commit -m "Based On OpenDDS $SHA"

    - name: Push Commit
      uses: ad-m/github-push-action@master
      with:
        directory: 'OpenDDS-Debian'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'ubuntu_20_04'

    - name: Lintian
      run: lintian --info --display-info opendds.deb
      continue-on-error: true
      if: always()

    - uses: actions/upload-artifact@v4
      with:
        name: deb
        path: opendds_*_*.deb
        compression-level: 0 # no compression
